// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testnativefiledocuments.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestNativeFileDocuments module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ImageToResize_SaveBuilder(
		testnativefiledocuments.proxies.ImageToResize _testImageToResize
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeFileDocuments.ACT_ImageToResize_Save");
		builder = builder.withParam("TestImageToResize", _testImageToResize);
		return builder;
	}

	public static void aCT_ImageToResize_Save(
		IContext context,
		testnativefiledocuments.proxies.ImageToResize _testImageToResize
	)
	{
		aCT_ImageToResize_SaveBuilder(
				_testImageToResize
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestCropImage_SaveBuilder(
		testnativefiledocuments.proxies.TestCropImage _testCropImage
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeFileDocuments.ACT_TestCropImage_Save");
		builder = builder.withParam("TestCropImage", _testCropImage);
		return builder;
	}

	public static void aCT_TestCropImage_Save(
		IContext context,
		testnativefiledocuments.proxies.TestCropImage _testCropImage
	)
	{
		aCT_TestCropImage_SaveBuilder(
				_testCropImage
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestDocument_SaveBuilder(
		testnativefiledocuments.proxies.TestDocument _testDocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeFileDocuments.ACT_TestDocument_Save");
		builder = builder.withParam("TestDocument", _testDocument);
		return builder;
	}

	public static void aCT_TestDocument_Save(
		IContext context,
		testnativefiledocuments.proxies.TestDocument _testDocument
	)
	{
		aCT_TestDocument_SaveBuilder(
				_testDocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestWriteFile_SaveBuilder(
		testnativefiledocuments.proxies.TestWriteFile _testWriteFile
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeFileDocuments.ACT_TestWriteFile_Save");
		builder = builder.withParam("TestWriteFile", _testWriteFile);
		return builder;
	}

	public static void aCT_TestWriteFile_Save(
		IContext context,
		testnativefiledocuments.proxies.TestWriteFile _testWriteFile
	)
	{
		aCT_TestWriteFile_SaveBuilder(
				_testWriteFile
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestWriteFileResult_DownloadBuilder(
		testnativefiledocuments.proxies.TestWriteFileResult _testWriteFileResult
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestNativeFileDocuments.ACT_TestWriteFileResult_Download");
		builder = builder.withParam("TestWriteFileResult", _testWriteFileResult);
		return builder;
	}

	public static void aCT_TestWriteFileResult_Download(
		IContext context,
		testnativefiledocuments.proxies.TestWriteFileResult _testWriteFileResult
	)
	{
		aCT_TestWriteFileResult_DownloadBuilder(
				_testWriteFileResult
			)
			.execute(context);
	}
}
