// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the NativeFileDocuments module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_NativeFileDocumentsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NativeFileDocuments.ASu_NativeFileDocuments");
		return builder;
	}

	public static void aSu_NativeFileDocuments(IContext context)
	{
		aSu_NativeFileDocumentsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bCo_NativeActionLogBuilder(
		nativefiledocuments.proxies.NativeActionLog _nativeActionLog
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NativeFileDocuments.BCo_NativeActionLog");
		builder = builder.withParam("NativeActionLog", _nativeActionLog);
		return builder;
	}

	public static boolean bCo_NativeActionLog(
		IContext context,
		nativefiledocuments.proxies.NativeActionLog _nativeActionLog
	)
	{
		Object result = bCo_NativeActionLogBuilder(
				_nativeActionLog
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sCE_DeviceLogFile_CleanupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NativeFileDocuments.SCE_DeviceLogFile_Cleanup");
		return builder;
	}

	public static void sCE_DeviceLogFile_Cleanup(IContext context)
	{
		sCE_DeviceLogFile_CleanupBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sCE_NativeActionLog_CleanupBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("NativeFileDocuments.SCE_NativeActionLog_Cleanup");
		return builder;
	}

	public static void sCE_NativeActionLog_Cleanup(IContext context)
	{
		sCE_NativeActionLog_CleanupBuilder().execute(context);
	}
}
