// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestImage_SaveBuilder(
		testmodule.proxies.TestImage _testImage
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestModule.ACT_TestImage_Save");
		builder = builder.withParam("TestImage", _testImage);
		return builder;
	}

	public static void aCT_TestImage_Save(
		IContext context,
		testmodule.proxies.TestImage _testImage
	)
	{
		aCT_TestImage_SaveBuilder(
				_testImage
			)
			.execute(context);
	}
}
