// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativefiledocuments.proxies;

public class DeviceLogFile extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeFileDocuments.DeviceLogFile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DeviceID("DeviceID"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		DeviceLogFile_Account("NativeFileDocuments.DeviceLogFile_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeviceLogFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DeviceLogFile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deviceLogFileMendixObject)
	{
		super(context, deviceLogFileMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, deviceLogFileMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativefiledocuments.proxies.DeviceLogFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativefiledocuments.proxies.DeviceLogFile(context, mendixObject);
	}

	public static nativefiledocuments.proxies.DeviceLogFile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativefiledocuments.proxies.DeviceLogFile.initialize(context, mendixObject);
	}

	public static java.util.List<nativefiledocuments.proxies.DeviceLogFile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nativefiledocuments.proxies.DeviceLogFile.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DeviceID
	 */
	public final java.lang.String getDeviceID()
	{
		return getDeviceID(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceID
	 */
	public final java.lang.String getDeviceID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceID.toString());
	}

	/**
	 * Set value of DeviceID
	 * @param deviceid
	 */
	public final void setDeviceID(java.lang.String deviceid)
	{
		setDeviceID(getContext(), deviceid);
	}

	/**
	 * Set value of DeviceID
	 * @param context
	 * @param deviceid
	 */
	public final void setDeviceID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deviceid)
	{
		getMendixObject().setValue(context, MemberNames.DeviceID.toString(), deviceid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DeviceLogFile_Account
	 */
	public final administration.proxies.Account getDeviceLogFile_Account() throws com.mendix.core.CoreException
	{
		return getDeviceLogFile_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceLogFile_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getDeviceLogFile_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DeviceLogFile_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DeviceLogFile_Account
	 * @param devicelogfile_account
	 */
	public final void setDeviceLogFile_Account(administration.proxies.Account devicelogfile_account)
	{
		setDeviceLogFile_Account(getContext(), devicelogfile_account);
	}

	/**
	 * Set value of DeviceLogFile_Account
	 * @param context
	 * @param devicelogfile_account
	 */
	public final void setDeviceLogFile_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account devicelogfile_account)
	{
		if (devicelogfile_account == null) {
			getMendixObject().setValue(context, MemberNames.DeviceLogFile_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DeviceLogFile_Account.toString(), devicelogfile_account.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativefiledocuments.proxies.DeviceLogFile that = (nativefiledocuments.proxies.DeviceLogFile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
